import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { 
  getFirestore, 
  collection, 
  doc, 
  getDocs, 
  setDoc, 
  deleteDoc, 
  query, 
  orderBy,
  Firestore,
  getDocFromServer,
  getDoc
} from 'firebase/firestore';
import { 
  getAuth, 
  signInWithEmailAndPassword, 
  createUserWithEmailAndPassword,
  signOut, 
  onAuthStateChanged, 
  Auth, 
  User,
  GoogleAuthProvider,
  signInWithPopup
} from 'firebase/auth';
import { Submission, SubmissionItem, ActivityLog, NpwpRecord } from './types';

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: {
      providerId?: string | null;
      email?: string | null;
    }[];
  }
}

// Global variable holding the active configuration
let firebaseApp: FirebaseApp | null = null;
let firestoreDb: Firestore | null = null;
let firebaseAuth: Auth | null = null;
let currentUser: User | null = null;

// Helper to check and parse stored config
export const getStoredFirebaseConfig = (): any | null => {
  // Check if environment variables are provided first, else fall back to default hardcoded config
  const envApiKey = import.meta.env.VITE_FIREBASE_API_KEY;
  const envProjectId = import.meta.env.VITE_FIREBASE_PROJECT_ID;
  
  if (envApiKey && envProjectId) {
    return {
      apiKey: envApiKey,
      authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || `${envProjectId}.firebaseapp.com`,
      databaseURL: import.meta.env.VITE_FIREBASE_DATABASE_URL || `https://${envProjectId}-default-rtdb.asia-southeast1.firebasedatabase.app`,
      projectId: envProjectId,
      storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || `${envProjectId}.firebasestorage.app`,
      messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
      appId: import.meta.env.VITE_FIREBASE_APP_ID || '',
      measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID || ''
    };
  }

  // Static configuration hardcoded securely as requested to avoid any conflicts
  return {
    apiKey: "AIzaSyDfIvUOLqAULR9eKy0rkqJfY_99Q4rxy2M",
    authDomain: "pencatatan-voucher-perusahaan.firebaseapp.com",
    databaseURL: "https://pencatatan-voucher-perusahaan-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "pencatatan-voucher-perusahaan",
    storageBucket: "pencatatan-voucher-perusahaan.firebasestorage.app",
    messagingSenderId: "5344554002",
    appId: "1:5344554002:web:9137a500fbb8f3223b7ccb",
    measurementId: "G-1249N852Y5"
  };
};

// TWO-WAY DATA SCHEMAS TRANSLATION / MAPPER UTILITIES
export const mapFirestoreToSubmission = (docId: string, data: any): Submission => {
  let firestoreItems = Array.isArray(data.items) ? data.items : [];
  
  // Reconstruct nested item array if the old record was stored flat at the top-level
  if (firestoreItems.length === 0) {
    const itemName = data.isi_invoice || data.isiInvoice || data.item || data.nama || data.jenis_pengajuan || data.jenisPengajuan || data.jenis || 'Item Penyerahan';
    const itemTotal = parseFloat(data.total_nominal || data.totalNominal || data.nominal || data.total || '0') || 0;
    const itemQty = data.qty !== undefined ? String(data.qty) : (data.jumlahVolume || '1');
    const itemKeterangan = data.no_invoice || data.noInvoice || data.keterangan || '';
    
    firestoreItems = [{
      id: `item-${docId}-flat`,
      no: 1,
      nama: itemName,
      qty: itemQty,
      nominal: itemTotal,
      totalNominal: itemTotal,
      noInvoice: itemKeterangan,
      keterangan: itemKeterangan,
      status: data.status || 'Belum Lunas'
    }];
  }

  // Map internal database nested maps to UI SubmissionItem structures
  const mappedItems: SubmissionItem[] = firestoreItems.map((fi: any, idx: number) => {
    let ket = '';
    if (fi.keterangan !== undefined) {
      ket = fi.keterangan || '';
    } else if (fi.noInvoice !== undefined) {
      const isAutoGenerated = typeof fi.noInvoice === 'string' && fi.noInvoice.startsWith('INV-sub-');
      ket = isAutoGenerated ? '' : (fi.noInvoice || '');
    }
    return {
      id: fi.id || `item-${docId}-${idx}-${Math.random().toString(36).substr(2, 4)}`,
      no: fi.no || (idx + 1),
      item: fi.nama || fi.item || 'Item Penyerahan',
      jumlahVolume: fi.qty !== undefined ? `${fi.qty}` : (fi.jumlahVolume || '1'),
      total: fi.totalNominal || fi.nominal || fi.total || 0,
      keterangan: ket
    };
  });

  // Extract date correctly from Firestore Timestamp, milliseconds, or string representation
  let createdAtStr = new Date().toISOString();
  const rawCreatedAt = data.createdAt || data.created_at || data.tanggal;
  if (rawCreatedAt) {
    if (typeof rawCreatedAt.toDate === 'function') {
      createdAtStr = rawCreatedAt.toDate().toISOString();
    } else if (rawCreatedAt.seconds) {
      createdAtStr = new Date(rawCreatedAt.seconds * 1000).toISOString();
    } else {
      createdAtStr = String(rawCreatedAt);
    }
  }

  // Determine which field holds the long document code (e.g. BKK-NMSA/VI/2026/10001)
  let docCode = '';
  const candidates = [
    data.no_invoice,
    data.noInvoice,
    data.kode,
    data.code
  ];
  for (const c of candidates) {
    if (typeof c === 'string' && c.length > 5) {
      docCode = c;
      break;
    }
  }
  if (!docCode) {
    docCode = data.no_invoice || data.noInvoice || data.kode || data.code || 'BKK-HO/VI/2026/10001';
  }

  const firstItem = firestoreItems[0] || {};
  const isDocLunas = data.status === 'Lunas' || firstItem.status === 'Lunas' || data.dibayarkanDengan === 'Cek/Transfer' || data.dibayarkan_dengan === 'Cek/Transfer';
  const finalStatus = data.status || firstItem.status || (isDocLunas ? 'Lunas' : 'Belum Lunas');

  return {
    id: docId,
    lokasi: data.lokasi || firstItem.lokasi || 'Lt. 1',
    tanggal: data.tanggal || data.tanggal_pengajuan || firstItem.tanggal || new Date().toISOString().split('T')[0],
    jenisPengajuan: data.jenisPengajuan || data.jenis_pengajuan || data.jenis || firstItem.jenis || 'Biaya Gaji',
    kode: docCode,
    dibayarkanKepada: data.dibayarkanKepada || data.dibayarkan_kepada || 'Penerima',
    dibayarkanDengan: data.dibayarkanDengan || data.dibayarkan_dengan || (finalStatus === 'Lunas' ? 'Cek/Transfer' : 'Tunai'),
    status: finalStatus as 'Lunas' | 'Belum Lunas',
    notes: data.notes || data.catatan || data.catatan_tambahan || data.catatanTambahan || '',
    
    // Corporate signatures support
    dibuatOleh: data.dibuatOleh || data.createdByEmail || 'Nur Wahyudi',
    disetujuiOleh: data.disetujuiOleh || 'Harijon',
    diverifikasiOleh: data.diverifikasiOleh || 'Andi Dhiya Salsabila',
    diverifikasiJabatan: data.diverifikasiJabatan || 'Keuangan',
    disetujuiOleh2: data.disetujuiOleh2 || 'H. A. Nursyam Halid',
    disetujuiJabatan2: data.disetujuiJabatan2 || 'Direktur Utama',
    dibukukanOleh: data.dibukukanOleh || 'Sri Ekowati',
    dibukukanJabatan: data.dibukukanJabatan || 'Accounting',

    // Google Drive attachment support
    googleDriveFileUrl: data.googleDriveFileUrl || '',
    googleDriveFileName: data.googleDriveFileName || '',
    googleDriveFiles: data.googleDriveFiles || (data.googleDriveFileUrl ? [{ url: data.googleDriveFileUrl, name: data.googleDriveFileName || 'Buka di Drive' }] : []),
    buktiPembayaran: data.buktiPembayaran || undefined,

    // Invoice properties mapping
    isInvoice: !!data.isInvoice,
    invoiceNumber: data.invoiceNumber || '',
    invoiceDate: data.invoiceDate || '',
    invoiceAmount: typeof data.invoiceAmount === 'number' ? data.invoiceAmount : undefined,

    // Petty Cash properties mapping
    isPettyCash: !!data.isPettyCash,
    pettyCashCustodian: data.pettyCashCustodian || '',
    pettyCashFile: data.pettyCashFile || undefined,

    items: mappedItems,
    createdAt: createdAtStr,
    deletedPageIds: Array.isArray(data.deletedPageIds) ? data.deletedPageIds : []
  };
};

// Deeply sanitize objects to replace undefined keys or values with null/empty types to prevent Firestore write crashes
export const cleanUndefined = (obj: any): any => {
  if (obj === null || obj === undefined) {
    return null;
  }
  if (obj instanceof Date) {
    return obj;
  }
  if (Array.isArray(obj)) {
    return obj.map(item => cleanUndefined(item));
  }
  if (typeof obj === 'object') {
    const cleaned: any = {};
    for (const key of Object.keys(obj)) {
      const val = obj[key];
      if (val !== undefined) {
        cleaned[key] = cleanUndefined(val);
      }
    }
    return cleaned;
  }
  return obj;
};

// Safe helper to strip huge Base64 data URLs (> 300 KB) from Firestore documents to prevent 1MB limit crash
export const sanitizeUrlForFirestore = (url: string | null | undefined, docName: string = 'Dokumen'): string => {
  if (!url) return '';
  // If it's a huge Base64 string that will overflow Firestore's 1MB limit
  if (url.startsWith('data:') && url.length > 300000) {
    console.warn(`⚠️ URL for "${docName}" is a massive Base64 payload (${(url.length / 1024 / 1024).toFixed(2)} MB). Excluded from Firestore document body to comply with 1MB limit.`);
    return `[LOCAL_BASE64_ATTACHMENT:${docName}]`;
  }
  return url;
};

export const mapSubmissionToFirestore = (
  sub: Submission, 
  userEmail?: string, 
  userId?: string,
  userCompanyId: string = 'nmsa',
  userCompanyName: string = 'PT Nusantara Mineral Sukses Abadi'
): any => {
  const finalStatus = sub.status || (sub.dibayarkanDengan === 'Cek/Transfer' ? 'Lunas' : 'Belum Lunas');
  const isLunas = finalStatus === 'Lunas';
  const computedTotal = Array.isArray(sub.items) ? sub.items.reduce((sum, item) => sum + (item.total || 0), 0) : 0;
  const firstItemKeterangan = (sub.items && sub.items[0]?.keterangan) || '';
  const firstItemName = (sub.items && sub.items[0]?.item) || '';

  let shortKode = 'HO';
  if (sub.kode) {
    const upperSubKode = sub.kode.toUpperCase();
    if (upperSubKode.includes('LP')) {
      shortKode = 'LP';
    } else if (upperSubKode.includes('HO')) {
      shortKode = 'HO';
    } else {
      shortKode = userCompanyId ? userCompanyId.toUpperCase() : 'HO';
    }
  }

  const subItemsList = Array.isArray(sub.items) ? sub.items : [];
  const cleanItems = subItemsList.map((item, idx) => {
    // Extract numbers from volume (e.g. "1 Lot" -> 1, "5 Box" -> 5)
    const qtyStr = String(item.jumlahVolume || '1');
    const parsedQty = parseInt(qtyStr.replace(/[^0-9]/g, '')) || 1;
    
    return {
      nama: item.item || '',
      nominal: item.total || 0, 
      qty: parsedQty,
      jenis: sub.jenisPengajuan || '',
      kode: shortKode,
      lokasi: sub.lokasi || 'Lt. 1',
      noInvoice: item.keterangan || '',
      keterangan: item.keterangan || '',
      status: finalStatus,
      tanggal: sub.tanggal || '',
      tglBayar: isLunas && sub.tanggal ? new Date(sub.tanggal) : null,
      totalNominal: item.total || 0
    };
  });

  return {
    // Both camelCase and snake_case fields for total backwards compatibility
    catatan: sub.notes || '',
    catatan_tambahan: sub.notes || '',
    catatanTambahan: sub.notes || '',
    companyId: userCompanyId,
    companyName: userCompanyName,
    company_id: userCompanyId,
    company_name: userCompanyName,
    createdAt: new Date(),
    created_at: new Date(),
    createdBy: userId || 'pwsDJv3bKHQamy89PDaAeCoZQcU2',
    createdByEmail: userEmail || 'admin@nmsa.com',
    dibayarkanKepada: sub.dibayarkanKepada || '',
    dibayarkan_kepada: sub.dibayarkanKepada || '',
    dibayarkanDengan: sub.dibayarkanDengan || 'Tunai',
    dibayarkan_dengan: sub.dibayarkanDengan || 'Tunai',
    status: finalStatus,
    totalNominal: computedTotal,
    total_nominal: computedTotal,
    noInvoice: sub.kode || '',
    no_invoice: sub.kode || '',
    isi_invoice: firstItemName,
    isiInvoice: firstItemName,
    files: [],
    
    // Google Drive attachment support (with Firestore 1MB limit safety)
    googleDriveFileUrl: sanitizeUrlForFirestore(sub.googleDriveFileUrl, sub.googleDriveFileName || 'Lampiran'),
    googleDriveFileName: sub.googleDriveFileName || '',
    googleDriveFiles: Array.isArray(sub.googleDriveFiles)
      ? sub.googleDriveFiles.map(f => ({
          ...f,
          url: sanitizeUrlForFirestore(f.url, f.name || 'Lampiran')
        }))
      : [],

    items: cleanItems,
    updatedAt: new Date(),
    updated_at: new Date(),
    
    // Double save native fields so pulling it back preserves signatures
    id: sub.id,
    isInvoice: !!sub.isInvoice,
    invoiceNumber: sub.invoiceNumber || '',
    invoiceDate: sub.invoiceDate || '',
    invoiceAmount: typeof sub.invoiceAmount === 'number' ? sub.invoiceAmount : null,
    buktiPembayaran: sub.buktiPembayaran ? {
      ...sub.buktiPembayaran,
      url: sanitizeUrlForFirestore(sub.buktiPembayaran.url, sub.buktiPembayaran.name || 'Bukti Pembayaran')
    } : null,

    isPettyCash: !!sub.isPettyCash,
    pettyCashCustodian: sub.pettyCashCustodian || '',
    pettyCashFile: sub.pettyCashFile ? {
      ...sub.pettyCashFile,
      url: sanitizeUrlForFirestore(sub.pettyCashFile.url, sub.pettyCashFile.name || 'Laporan Petty Cash')
    } : null,
    
    lokasi: sub.lokasi || 'Lt. 1',
    tanggal: sub.tanggal || '',
    jenisPengajuan: sub.jenisPengajuan || '',
    jenis_pengajuan: sub.jenisPengajuan || '',
    jenis: sub.jenisPengajuan || '',
    kode: shortKode,
    dibuatOleh: sub.dibuatOleh || '',
    disetujuiOleh: sub.disetujuiOleh || '',
    diverifikasiOleh: sub.diverifikasiOleh || '',
    diverifikasiJabatan: sub.diverifikasiJabatan || '',
    disetujuiOleh2: sub.disetujuiOleh2 || '',
    disetujuiJabatan2: sub.disetujuiJabatan2 || '',
    dibukukanOleh: sub.dibukukanOleh || '',
    dibukukanJabatan: sub.dibukukanJabatan || '',
    deletedPageIds: sub.deletedPageIds || []
  };
};

export const getUserProfileFromFirestore = async (uid: string): Promise<any> => {
  if (!isFirebaseConfigured() || !firestoreDb) return null;
  try {
    const docRef = doc(firestoreDb, 'users', uid);
    const snap = await getDoc(docRef);
    if (snap.exists()) {
      const data = snap.data();
      if (data?.companyId) {
        setActiveCompanyId(data.companyId);
      }
      return data;
    }
  } catch (err) {
    console.warn('Silent read rejection - failed to fetch user profile:', err);
  }
  return null;
};

let activeCompanyId: string = 'nmsa';
export const getActiveCompanyId = () => activeCompanyId;
export const setActiveCompanyId = (id: string) => {
  activeCompanyId = id.toLowerCase().trim();
};

export const getCompanyProfileFromFirestore = async (companyId: string): Promise<any> => {
  if (!isFirebaseConfigured() || !firestoreDb) return null;
  const cleanId = companyId.toLowerCase().trim();
  setActiveCompanyId(cleanId);
  try {
    const docRef = doc(firestoreDb, 'companies', cleanId);
    const snap = await getDoc(docRef);
    if (snap.exists()) {
      const data = snap.data();
      // Auto-load shared Google Drive settings from Firestore to achieve zero-friction default connection!
      if (Array.isArray(data.googleDrives) && data.googleDrives.length > 0) {
        console.log('🔄 Auto-loaded company-shared Google Drive settings from Firestore:', data.googleDrives.length, 'drives');
        localStorage.setItem('NUSANTARA_CONNECTED_DRIVES', JSON.stringify(data.googleDrives));
        const activeDrive = data.googleDrives.find((d: any) => !d.isExpired && (d.quotaLimit - d.quotaUsed > 10 * 1024 * 1024));
        const bestToken = activeDrive ? activeDrive.accessToken : (data.googleDrives[0]?.accessToken || null);
        if (bestToken) {
          localStorage.setItem('NUSANTARA_GOOGLE_DRIVE_TOKEN', bestToken);
        }
      }
      return data;
    }
  } catch (err) {
    console.warn('Silent read rejection - failed to fetch company profile:', err);
  }
  return null;
};

export const loadAllCompaniesFromFirestore = async (): Promise<any[]> => {
  if (!isFirebaseConfigured() || !firestoreDb) return [];
  try {
    const colRef = collection(firestoreDb, 'companies');
    const snap = await getDocs(colRef);
    const result: any[] = [];
    snap.forEach((doc) => {
      result.push(doc.data());
    });
    return result;
  } catch (err) {
    console.warn('Silent read rejection - failed to fetch companies:', err);
  }
  return [];
};

export const registerUserToFirebase = async (
  email: string, 
  password: string, 
  fullName: string, 
  role: string,
  companyId: string = 'nmsa',
  companyName: string = 'PT Nusantara Mineral Sukses Abadi'
): Promise<User> => {
  if (!firebaseAuth) {
    throw new Error('Firebase Auth is not initialized. Please configure credentials first.');
  }
  if (!firestoreDb) {
    throw new Error('Firestore is not initialized. Please configure credentials first.');
  }
  try {
    const creds = await createUserWithEmailAndPassword(firebaseAuth, email, password);
    const user = creds.user;
    
    // Wait for the auth session to populate, then record the user under users/
    await setDoc(doc(firestoreDb, 'users', user.uid), {
      uid: user.uid,
      email: user.email,
      fullName: fullName,
      role: role ?? 'User',
      companyId: companyId.toLowerCase().trim(),
      companyName: companyName,
      createdAt: new Date().toISOString()
    });

    // Check if the company document already exists; if not, create it with user provided/standard fallbacks
    const companyCleanId = companyId.toLowerCase().trim();
    const companyRef = doc(firestoreDb, 'companies', companyCleanId);
    const companySnap = await getDoc(companyRef);
    
    if (!companySnap.exists()) {
      await setDoc(companyRef, {
        id: companyCleanId,
        code: companyCleanId.toUpperCase(),
        name: companyName,
        fullName: companyName,
        defaultJenis: 'Operasional Kantor',
        defaultKode: `BKK-${companyCleanId.toUpperCase()}/V/2026/10001`,
        defaultLokasi: 'Lt.1',
        displayName: `Invoice-${companyCleanId.toUpperCase()}`,
        icon: '🏢',
        isActive: true,
        no_invoice_prefix: `BKK-${companyCleanId.toUpperCase()}`,
        sigAccounting: role.toLowerCase().includes('accounting') || role.toLowerCase().includes('finance') ? fullName : 'Sri Ekowati',
        sigDibuat: fullName || 'Nur Wahyudi',
        sigDirKeuangan: 'Harijon',
        sigDirektur: 'Andi Nursyam Halid',
        sigDisetujui: 'Harijon',
        sigKeuangan: 'Andi Dhiya Salsabila',
        updatedAt: new Date().toISOString()
      });
      console.log(`🏬 Company metadata workspace created for [${companyCleanId}]`);
    }

    return user;
  } catch (error: any) {
    console.error('Authentication Signup Failed:', error);
    throw error;
  }
};

// Initialize Firebase dynamically based on configs
export const initializeFirebaseApp = (customConfig?: any): boolean => {
  const config = customConfig || getStoredFirebaseConfig();
  if (!config || !config.apiKey || !config.projectId) {
    firebaseApp = null;
    firestoreDb = null;
    firebaseAuth = null;
    return false;
  }

  try {
    const defaultApp = getApps().find(a => a.name === '[DEFAULT]');
    if (defaultApp) {
      firebaseApp = defaultApp;
    } else {
      firebaseApp = initializeApp(config);
    }
    // Set firestore and auth instances
    firestoreDb = getFirestore(firebaseApp);
    firebaseAuth = getAuth(firebaseApp);
    
    // Register listener for auth states
    onAuthStateChanged(firebaseAuth, (user) => {
      currentUser = user;
      console.log('📡 Auth State Modified. User logged in:', user?.email || 'NONE');
    });

    console.log('✅ Firebase initialized successfully with project:', config.projectId);
    
    // Asynchronously validate connection to Firestore
    testConnection();
    return true;
  } catch (e) {
    console.error('❌ Failed to initialize Firebase:', e);
    firebaseApp = null;
    firestoreDb = null;
    firebaseAuth = null;
    return false;
  }
};

// Asynchronously validate connection
async function testConnection() {
  if (!firestoreDb) return;
  try {
    await getDocFromServer(doc(firestoreDb, 'test', 'connection'));
    console.log('📡 Firestore database connection status: ACTIVE');
  } catch (error) {
    if (error instanceof Error && error.message.includes('the client is offline')) {
      console.warn("Please check your Firebase configuration or network status.");
    }
  }
}

// Helper to check configuration readiness
export const isFirebaseConfigured = (): boolean => {
  if (!firestoreDb) {
    return initializeFirebaseApp();
  }
  return true;
};

// Custom Firestore standard error reporter
function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: currentUser?.uid || 'ANONYMOUS_CLIENT_DASHBOARD',
      email: currentUser?.email || null,
      emailVerified: currentUser?.emailVerified || null,
      isAnonymous: currentUser?.isAnonymous || true,
      tenantId: currentUser?.tenantId || null,
      providerInfo: currentUser?.providerData || []
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

// Firebase Auth API Wrappers
export const loginToFirebase = async (email: string, password: string): Promise<User> => {
  if (!firebaseAuth) {
    throw new Error('Firebase Auth is not initialized. Please configure credentials first.');
  }
  try {
    const creds = await signInWithEmailAndPassword(firebaseAuth, email, password);
    currentUser = creds.user;
    return creds.user;
  } catch (error) {
    console.error('Authentication Failed:', error);
    throw error;
  }
};

export const logoutFromFirebase = async (): Promise<void> => {
  if (!firebaseAuth) return;
  await signOut(firebaseAuth);
  currentUser = null;
};

export const getFirebaseUser = (): User | null => {
  return currentUser;
};

export const registerAuthChangeListener = (callback: (user: User | null) => void): (() => void) => {
  if (!firebaseAuth) {
    return () => {};
  }
  return onAuthStateChanged(firebaseAuth, callback);
};

// ═════════ GOOGLE DRIVE / OAUTH PERSISTENCE UTILITIES ═════════
export interface ConnectedDrive {
  email: string;
  accessToken: string;
  displayName: string;
  photoURL?: string;
  quotaUsed: number;   // Bytes
  quotaLimit: number;  // Bytes
  lastChecked: string; // ISO String
  isExpired?: boolean;
  issuedAt?: number;   // Epoch timestamp of token issue
}

let googleDriveTokenMemory: string | null = null;

export const setGoogleDriveToken = (token: string | null) => {
  googleDriveTokenMemory = token;
  if (token) {
    localStorage.setItem('NUSANTARA_GOOGLE_DRIVE_TOKEN', token);
  } else {
    localStorage.removeItem('NUSANTARA_GOOGLE_DRIVE_TOKEN');
  }
};

export const getConnectedDrives = (): ConnectedDrive[] => {
  try {
    const raw = localStorage.getItem('NUSANTARA_CONNECTED_DRIVES');
    if (raw) {
      return JSON.parse(raw);
    }
  } catch (e) {
    console.error('Failed to parse connected drives list', e);
  }

  // Fallback / migration for legacy single token
  const legacyToken = localStorage.getItem('NUSANTARA_GOOGLE_DRIVE_TOKEN');
  if (legacyToken) {
    const initialDrive: ConnectedDrive = {
      email: 'yudiakungaming@gmail.com', // fallback as requested by user
      accessToken: legacyToken,
      displayName: 'yudiakungaming@gmail.com',
      quotaUsed: 0,
      quotaLimit: 15 * 1024 * 1024 * 1024, // 15 GB
      lastChecked: new Date().toISOString()
    };
    return [initialDrive];
  }
  return [];
};

export const loadConnectedDrivesFromFirestore = async (companyId: string = 'nmsa'): Promise<ConnectedDrive[]> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    return getConnectedDrives();
  }
  try {
    const compId = companyId || activeCompanyId || 'nmsa';
    const companyRef = doc(firestoreDb, 'companies', compId);
    const snap = await getDoc(companyRef);
    if (snap.exists()) {
      const data = snap.data();
      if (data && Array.isArray(data.googleDrives) && data.googleDrives.length > 0) {
        const cloudDrives: ConnectedDrive[] = data.googleDrives;
        localStorage.setItem('NUSANTARA_CONNECTED_DRIVES', JSON.stringify(cloudDrives));
        const activeDrive = cloudDrives.find(d => !d.isExpired && (d.quotaLimit - d.quotaUsed > 10 * 1024 * 1024));
        const bestToken = activeDrive ? activeDrive.accessToken : (cloudDrives[0]?.accessToken || null);
        setGoogleDriveToken(bestToken);
        if (activeDrive) {
          localStorage.setItem('NUSANTARA_LAST_ACTIVE_EMAIL', activeDrive.email);
        }
        return cloudDrives;
      }
    }
  } catch (err) {
    console.warn('Could not load connected drives from Firestore:', err);
  }
  return getConnectedDrives();
};

export const getActiveGoogleDriveAccount = (): { email: string; displayName?: string; photoURL?: string } | null => {
  const drives = getConnectedDrives();
  if (drives.length > 0) {
    const active = drives.find(d => !d.isExpired) || drives[0];
    return {
      email: active.email,
      displayName: active.displayName,
      photoURL: active.photoURL
    };
  }
  const lastEmail = localStorage.getItem('NUSANTARA_LAST_ACTIVE_EMAIL');
  if (lastEmail) {
    return { email: lastEmail };
  }
  return null;
};

export const saveConnectedDrives = async (drives: ConnectedDrive[]) => {
  try {
    localStorage.setItem('NUSANTARA_CONNECTED_DRIVES', JSON.stringify(drives));
    // Synced with legacy single token to maintain maximum compatibility with existing code
    const activeDrive = drives.find(d => !d.isExpired && (d.quotaLimit - d.quotaUsed > 10 * 1024 * 1024));
    const bestToken = activeDrive ? activeDrive.accessToken : (drives[0]?.accessToken || null);
    setGoogleDriveToken(bestToken);

    if (activeDrive) {
      localStorage.setItem('NUSANTARA_LAST_ACTIVE_EMAIL', activeDrive.email);
    }

    // Persist to Firestore under company document to share with all users and all menus of this company!
    const targetCompId = activeCompanyId || 'nmsa';
    if (firestoreDb && targetCompId) {
      const companyRef = doc(firestoreDb, 'companies', targetCompId);
      await setDoc(companyRef, {
        googleDrives: cleanUndefined(drives),
        updatedAt: new Date().toISOString()
      }, { merge: true });
      console.log(`☁️ Synced Google Drive credentials to Firestore for company: ${targetCompId}`);
    }

    // Notify all active application components about the updated Drive account
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('nusantara-drive-updated', {
        detail: {
          drives,
          activeAccount: getActiveGoogleDriveAccount(),
          hasToken: !!bestToken
        }
      }));
    }
  } catch (e) {
    console.error('Failed to save connected drives list', e);
  }
};

export const fetchDriveQuotaMetadata = async (token: string): Promise<{
  email: string;
  displayName: string;
  photoURL?: string;
  quotaUsed: number;
  quotaLimit: number;
}> => {
  const response = await fetch('https://www.googleapis.com/drive/v3/about?fields=user,storageQuota', {
    headers: {
      'Authorization': `Bearer ${token}`
    }
  });
  if (!response.ok) {
    throw new Error(`Failed to fetch Drive quota details: ${response.statusText}`);
  }
  const data = await response.json();
  return {
    email: data.user?.emailAddress || 'yudiakungaming@gmail.com',
    displayName: data.user?.displayName || 'Google Drive',
    photoURL: data.user?.photoLink || '',
    quotaUsed: parseInt(data.storageQuota?.usage || '0', 10),
    quotaLimit: parseInt(data.storageQuota?.limit || '16106127360', 10) // default 15GB in bytes
  };
};

export const refreshAllDrivesQuota = async (): Promise<ConnectedDrive[]> => {
  const drives = getConnectedDrives();
  if (drives.length === 0) return [];

  const updatedDrives = await Promise.all(
    drives.map(async (drive) => {
      try {
        const meta = await fetchDriveQuotaMetadata(drive.accessToken);
        return {
          ...drive,
          email: meta.email,
          displayName: meta.displayName,
          photoURL: meta.photoURL,
          quotaUsed: meta.quotaUsed,
          quotaLimit: meta.quotaLimit,
          lastChecked: new Date().toISOString(),
          isExpired: false
        };
      } catch (err) {
        console.warn(`Error refreshing quota for Drive ${drive.email}:`, err);
        // Mark as expired if unauthorized or other connection failure
        return {
          ...drive,
          isExpired: true
        };
      }
    })
  );

  saveConnectedDrives(updatedDrives);
  return updatedDrives;
};

export const autoCleanDriveFolders = async (activeSubmissions: any[]) => {
  const token = getStoredGoogleDriveToken();
  if (!token) return;

  try {
    console.log('[Auto-Sync] Memeriksa sinkronisasi data dengan Google Drive...');
    // Real implementation would be too dangerous to blindly delete folders.
    // The deletion is already handled reliably in the handleDelete function.
  } catch (error) {
    console.error('[Auto-Sync] Error during auto clean:', error);
  }
};

export const deleteGoogleDriveFile = async (fileId: string): Promise<void> => {
  const token = await ensureValidDriveToken();
  if (!token) {
    throw new Error('Google Drive token not available');
  }

  try {
    const response = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}`, {
      method: 'DELETE',
      headers: {
        Authorization: `Bearer ${token}`
      }
    });

    if (!response.ok) {
      if (response.status === 404) {
        console.log(`[Google Drive] File/folder ${fileId} already deleted or not found.`);
        return;
      }
      const errorData = await response.json().catch(() => null);
      throw new Error(`Failed to delete file/folder: ${response.status} ${response.statusText} - ${errorData?.error?.message || ''}`);
    }
    console.log(`[Google Drive] Successfully deleted file/folder ${fileId}`);
  } catch (error) {
    console.error(`[Google Drive] Error deleting file/folder ${fileId}:`, error);
    throw error;
  }
};

export const getStoredGoogleDriveToken = (): string | null => {
  // Let's implement the smart auto-chain priority switching:
  // We return the first valid, unexpired token that has remaining space (> 10MB free)
  const drives = getConnectedDrives();
  if (drives.length === 0) {
    if (googleDriveTokenMemory) return googleDriveTokenMemory;
    try {
      return localStorage.getItem('NUSANTARA_GOOGLE_DRIVE_TOKEN');
    } catch {
      return null;
    }
  }

  // Find first active, unexpired drive with at least 15MB free space left
  const availableDrive = drives.find(d => {
    if (d.isExpired) return false;
    
    // Check if token is older than 50 minutes (3000 seconds)
    const tokenAge = Date.now() - (d.issuedAt || 0);
    if (d.issuedAt && tokenAge > 3000 * 1000) {
      return false; // Token has expired or is about to expire
    }

    const remainingBytes = d.quotaLimit - d.quotaUsed;
    return remainingBytes > 15 * 1024 * 1024; // 15MB
  });

  if (availableDrive) {
    return availableDrive.accessToken;
  }

  // If all are full or expired, fallback to the first active one that isn't expired by time
  const fallbackDrive = drives.find(d => {
    if (d.isExpired) return false;
    const tokenAge = Date.now() - (d.issuedAt || 0);
    if (d.issuedAt && tokenAge > 3000 * 1000) return false;
    return true;
  });
  
  return fallbackDrive ? fallbackDrive.accessToken : null;
};

// Helper function to silently auto-refresh token if it's expired or about to expire
export const ensureValidDriveToken = async (): Promise<string | null> => {
  // OPSI B: Coba ambil token dari Service Account (Backend) terlebih dahulu
  try {
    const res = await fetch('/api/drive-token');
    if (res.ok) {
      const data = await res.json();
      if (data.success && data.accessToken) {
        console.log('✅ Menggunakan Service Account untuk Google Drive');
        setGoogleDriveToken(data.accessToken);
        return data.accessToken;
      }
    }
  } catch (err) {
    // Service Account token tidak tersedia, menggunakan User Login
  }

  // Check if current stored token is valid
  let token = getStoredGoogleDriveToken();
  if (token) {
    return token; // Still valid
  }

  // Check if token exists in Firestore company document (e.g. from another tab or previous login)
  try {
    const cloudDrives = await loadConnectedDrivesFromFirestore();
    token = getStoredGoogleDriveToken();
    if (token) return token;
  } catch (e) {}

  // If we reach here, it means tokens are expired or missing. Try to auto-refresh the last active account.
  const lastEmail = localStorage.getItem('NUSANTARA_LAST_ACTIVE_EMAIL');
  if (lastEmail) {
    try {
      console.log('🔄 Auto-refreshing Google Drive token in the background for:', lastEmail);
      const result = await googleDriveLogin(lastEmail, false);
      return result.accessToken;
    } catch (err) {
      console.warn('⚠️ Background auto-refresh attempt notice:', err);
    }
  }
  
  // Return whatever fallback token exists if any
  return googleDriveTokenMemory || localStorage.getItem('NUSANTARA_GOOGLE_DRIVE_TOKEN');
};

// Periodic Background Auto-Keeper for Google Drive connection
let tokenAutoRefreshIntervalId: any = null;
let isRefreshingDriveToken = false;

export const startGoogleDriveTokenAutoRefresh = (intervalMinutes = 3): (() => void) => {
  if (typeof window === 'undefined') return () => {};

  const runKeepAliveCheck = async () => {
    if (isRefreshingDriveToken) return;
    isRefreshingDriveToken = true;

    try {
      // 1. Check if we have drives connected
      const drives = getConnectedDrives();
      const lastEmail = localStorage.getItem('NUSANTARA_LAST_ACTIVE_EMAIL');
      
      if (drives.length === 0 && !lastEmail) {
        // Try fetching shared company drive from Firestore
        await loadConnectedDrivesFromFirestore();
      }

      const activeDrives = getConnectedDrives();
      if (activeDrives.length > 0 || lastEmail) {
        // Check if current token needs refresh (> 45 min old or expired)
        const currentToken = getStoredGoogleDriveToken();
        if (!currentToken) {
          console.log('⏰ [Google Drive Auto-Refresh] Token kedaluwarsa, memperbarui otomatis...');
          await ensureValidDriveToken();
        } else {
          // Token is present, periodically refresh quotas & verify
          try {
            await refreshAllDrivesQuota();
          } catch (qErr) {
            console.warn('[Google Drive Auto-Refresh] Quota ping check:', qErr);
          }
        }
      }
    } catch (err) {
      console.warn('[Google Drive Auto-Refresh] Background check error:', err);
    } finally {
      isRefreshingDriveToken = false;
    }
  };

  // Run immediately on setup
  runKeepAliveCheck();

  // Clear existing interval if any
  if (tokenAutoRefreshIntervalId) {
    clearInterval(tokenAutoRefreshIntervalId);
  }

  // Set interval (every 3 minutes by default)
  tokenAutoRefreshIntervalId = setInterval(runKeepAliveCheck, intervalMinutes * 60 * 1000);

  // Also trigger when tab becomes visible or gains focus!
  const onVisibilityChange = () => {
    if (document.visibilityState === 'visible') {
      runKeepAliveCheck();
    }
  };

  const onWindowFocus = () => {
    runKeepAliveCheck();
  };

  window.addEventListener('visibilitychange', onVisibilityChange);
  window.addEventListener('focus', onWindowFocus);

  return () => {
    if (tokenAutoRefreshIntervalId) {
      clearInterval(tokenAutoRefreshIntervalId);
      tokenAutoRefreshIntervalId = null;
    }
    window.removeEventListener('visibilitychange', onVisibilityChange);
    window.removeEventListener('focus', onWindowFocus);
  };
};

export const googleDriveLogin = async (
  loginHint?: string,
  forceSelectAccount = false
): Promise<{ user: User; accessToken: string; driveDetails?: any }> => {
  const config = getStoredFirebaseConfig();
  if (!config) {
    throw new Error('Database autentikasi belum beroperasi.');
  }

  // To prevent changing the currently logged-in portal user (which swaps user profiles,
  // causing data loss or falling back to default lists), we initialize a completely separate,
  // isolated secondary Firebase Auth instance solely for handling the Google Drive popup credentials!
  let secondaryApp;
  const secondaryAppName = 'drive-auth-temp-' + Math.random().toString(36).substring(2);
  try {
    secondaryApp = initializeApp(config, secondaryAppName);
  } catch (err) {
    console.error('Failed to init secondary app:', err);
    throw new Error('Gagal menyiapkan otentikasi Google Drive terisolasi.');
  }

  const secondaryAuth = getAuth(secondaryApp);
  const provider = new GoogleAuthProvider();
  // Request Google Drive File write/edit permissions - we use drive.file as full drive scope is restricted and blocked by Google without verification
  provider.addScope('https://www.googleapis.com/auth/drive.file');

  // Automatic previous account bypass logic
  let lastEmail = loginHint || localStorage.getItem('NUSANTARA_LAST_ACTIVE_EMAIL');
  if (!lastEmail) {
    const drives = getConnectedDrives();
    if (drives.length > 0) {
      lastEmail = drives[0].email;
    }
  }

  if (lastEmail && !forceSelectAccount) {
    provider.setCustomParameters({
      login_hint: lastEmail
    });
  } else {
    // Prompt account selection to make it extremely easy to connect multiple DIFFERENT accounts!
    provider.setCustomParameters({
      prompt: 'select_account'
    });
  }
  
  try {
    const result = await signInWithPopup(secondaryAuth, provider);
    const credential = GoogleAuthProvider.credentialFromResult(result);
    if (!credential?.accessToken) {
      throw new Error('Sesi otentikasi Google gagal menyuplai kunci akses (Access Token).');
    }
    
    // Fetch detailed metadata from Drive API for accurate storage & user matching
    let driveDetails = null;
    try {
      driveDetails = await fetchDriveQuotaMetadata(credential.accessToken);
    } catch (apiErr) {
      console.warn('Failed to fetch Drive metadata, using fallback details', apiErr);
      driveDetails = {
        email: result.user.email || 'yudiakungaming@gmail.com',
        displayName: result.user.displayName || 'Google Drive',
        photoURL: result.user.photoURL || '',
        quotaUsed: 0,
        quotaLimit: 15 * 1024 * 1024 * 1024
      };
    }

    // Check if storage is full (quotaUsed is at least 98% of limit or less than 15MB remaining)
    const limit = driveDetails.quotaLimit || 15 * 1024 * 1024 * 1024;
    const used = driveDetails.quotaUsed || 0;
    const remains = limit - used;
    const isFull = remains <= 15 * 1024 * 1024; // Less than 15MB free

    if (isFull) {
      const usedGB = Math.round(used / (1024 * 1024 * 1024) * 100) / 100;
      const limitGB = Math.round(limit / (1024 * 1024 * 1024));
      window.alert(
        `Penyimpanan Google Drive "${driveDetails.email}" telah penuh (Terisi: ${usedGB} GB dari ${limitGB} GB).\n\nSilakan pilih akun Google Drive cadangan atau akun Google ke-2 Anda untuk melanjutkan penyimpanan secara otomatis tanpa hambatan.`
      );

      // Clean up secondary auth session before switching
      try {
        await secondaryAuth.signOut();
      } catch (e) {}

      // Recursively connect backup/second account by forcing account selector
      return googleDriveLogin(undefined, true);
    }

    // Store as last active email since it has available storage space
    localStorage.setItem('NUSANTARA_LAST_ACTIVE_EMAIL', driveDetails.email);

    // Load existing connected drives list
    const currentDrives = getConnectedDrives();
    const newDrive: ConnectedDrive = {
      email: driveDetails.email,
      accessToken: credential.accessToken,
      displayName: driveDetails.displayName,
      photoURL: driveDetails.photoURL,
      quotaUsed: driveDetails.quotaUsed,
      quotaLimit: driveDetails.quotaLimit,
      lastChecked: new Date().toISOString(),
      isExpired: false,
      issuedAt: Date.now()
    };

    // Replace if email exists, otherwise index appends
    const index = currentDrives.findIndex(d => d.email.toLowerCase() === driveDetails.email.toLowerCase());
    if (index !== -1) {
      currentDrives[index] = newDrive;
    } else {
      currentDrives.push(newDrive);
    }

    await saveConnectedDrives(currentDrives);

    // Completely dispose of secondary auth session to keep memory clean
    try {
      await secondaryAuth.signOut();
    } catch (signoutErr) {
      console.warn('Silent signout error for secondary instance:', signoutErr);
    }

    return { user: result.user, accessToken: credential.accessToken, driveDetails };
  } catch (error: any) {
    console.error('Error Google Drive connection:', error);
    throw error;
  }
};

// ═════════ FIRESTORE REST DATA OPERATION IMPLEMENTATIONS ═════════

// Fetch submissions from Firestore, optionally filtered by user's companyId to achieve database segregation
export const loadSubmissionsFromFirestore = async (companyId?: string): Promise<Submission[]> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    throw new Error('Firebase is not initialized. Please provide correct configuration.');
  }

  const path = 'submissions';
  try {
    const q = query(collection(firestoreDb, path), orderBy('tanggal', 'desc'));
    const snapshot = await getDocs(q);
    const list: Submission[] = [];
    
    snapshot.forEach(docSnap => {
      // Apply mapping from user schema (with items details and timestamps) to our rich interface
      const data = docSnap.data();
      const mapped = mapFirestoreToSubmission(docSnap.id, data);
      
      // Filter by companyId client-side to be 100% immune from missing index errors
      if (!companyId || data.companyId === companyId || data.company_id === companyId) {
        list.push(mapped);
      }
    });
    
    return list;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, path);
    return [];
  }
};

// Fetch single submission from Firestore by its ID
export const getSubmissionFromFirestore = async (docId: string): Promise<Submission | null> => {
  if (!isFirebaseConfigured() || !firestoreDb) return null;
  try {
    const docRef = doc(firestoreDb, 'submissions', docId);
    const snap = await getDoc(docRef);
    if (snap.exists()) {
      return mapFirestoreToSubmission(snap.id, snap.data());
    }
  } catch (err) {
    console.warn('Error fetching single submission:', err);
  }
  return null;
};

// Put/Save single submission in Firestore under user's actual companyId
export const saveSubmissionToFirestore = async (
  submission: Submission, 
  userCompanyId: string = 'nmsa',
  userCompanyName: string = 'PT Nusantara Mineral Sukses Abadi'
): Promise<void> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    throw new Error('Firebase is not initialized.');
  }

  const path = `submissions`;
  try {
    // Map our rich React types to their exact expected database fields
    const fPayload = mapSubmissionToFirestore(
      submission, 
      currentUser?.email || 'admin@nmsa.com', 
      currentUser?.uid || 'pwsDJv3bKHQamy89PDaAeCoZQcU2',
      userCompanyId,
      userCompanyName
    );
    const cleanedPayload = cleanUndefined(fPayload);
    await setDoc(doc(firestoreDb, path, submission.id), cleanedPayload);
    console.log(`☁️ Submission ${submission.id} mapped and saved in Firestore under company ${userCompanyId}.`);
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `${path}/${submission.id}`);
  }
};

// Delete single submission from Firestore
export const deleteSubmissionFromFirestore = async (id: string): Promise<void> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    throw new Error('Firebase is not initialized.');
  }

  const path = `submissions`;
  try {
    await deleteDoc(doc(firestoreDb, path, id));
    console.log(`☁️ Submission ${id} deleted from Firestore.`);
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `${path}/${id}`);
  }
};

// Fetch activity logs from Firestore (or fallback to local if disconnected)
export const loadActivityLogsFromFirestore = async (companyId?: string): Promise<ActivityLog[]> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    // If not configured, load from localStorage
    try {
      const stored = localStorage.getItem('NUSANTARA_ACTIVITY_LOGS');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  }

  const path = 'activity_logs';
  try {
    const q = query(collection(firestoreDb, path), orderBy('timestamp', 'desc'));
    const snapshot = await getDocs(q);
    const list: ActivityLog[] = [];
    
    snapshot.forEach(docSnap => {
      const data = docSnap.data();
      list.push({
        id: docSnap.id,
        timestamp: data.timestamp || new Date().toISOString(),
        userId: data.userId || '',
        userEmail: data.userEmail || '',
        userName: data.userName || '',
        action: data.action || '',
        details: data.details || '',
        submissionId: data.submissionId || '',
        submissionCode: data.submissionCode || '',
        category: data.category || 'info'
      });
    });
    
    // Cache Firestore logs locally too
    localStorage.setItem('NUSANTARA_ACTIVITY_LOGS', JSON.stringify(list));
    return list;
  } catch (error) {
    console.warn('Silent read logs rejection - failed to fetch logs from Firestore:', error);
    try {
      const stored = localStorage.getItem('NUSANTARA_ACTIVITY_LOGS');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  }
};

// Push a single activity log to Firestore and local cache
export const saveActivityLogToFirestore = async (
  action: string,
  details: string,
  category: 'info' | 'success' | 'warning' = 'info',
  submissionId?: string,
  submissionCode?: string,
  userProfile?: any
): Promise<void> => {
  const logId = `log-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`;
  const timestamp = new Date().toISOString();
  
  const activeUser = currentUser;
  const userId = activeUser?.uid || 'anonymous';
  const userEmail = activeUser?.email || 'offline_user';
  const userName = userProfile?.fullName || activeUser?.email?.split('@')[0] || 'Sistem';

  const logPayload: ActivityLog = {
    id: logId,
    timestamp,
    userId,
    userEmail,
    userName,
    action,
    details,
    category,
    submissionId: submissionId || '',
    submissionCode: submissionCode || ''
  };

  // 1. Cache to local storage list first
  try {
    const stored = localStorage.getItem('NUSANTARA_ACTIVITY_LOGS');
    const list: ActivityLog[] = stored ? JSON.parse(stored) : [];
    const updatedList = [logPayload, ...list].slice(0, 500); // limit to latest 500 logs to prevent overflow
    localStorage.setItem('NUSANTARA_ACTIVITY_LOGS', JSON.stringify(updatedList));
  } catch (e) {
    console.warn('Failed to save log to localStorage:', e);
  }

  // 2. Write to Firestore if connected
  if (isFirebaseConfigured() && firestoreDb) {
    const path = 'activity_logs';
    try {
      await setDoc(doc(firestoreDb, path, logId), logPayload);
    } catch (err) {
      console.warn('Silent write logs rejection - failed to save log to Firestore:', err);
    }
  }
};

// Fetch NPWP Records from Firestore (or fallback to local)
export const loadNpwpRecordsFromFirestore = async (): Promise<NpwpRecord[]> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    try {
      const stored = localStorage.getItem('npwp_records_v1');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  }

  const path = 'npwp_records';
  try {
    const snapshot = await getDocs(collection(firestoreDb, path));
    const list: NpwpRecord[] = [];
    
    snapshot.forEach(docSnap => {
      const data = docSnap.data();
      if (data && data.companyName) {
        list.push({
          id: docSnap.id || data.id,
          companyName: data.companyName,
          npwpNumber: data.npwpNumber || '',
          address: data.address || '',
          kppName: data.kppName || '',
          taxStatus: data.taxStatus || 'PKP',
          contactPerson: data.contactPerson || '',
          notes: data.notes || '',
          createdAt: data.createdAt || new Date().toISOString()
        });
      }
    });
    
    if (list.length > 0) {
      localStorage.setItem('npwp_records_v1', JSON.stringify(list));
    }
    return list;
  } catch (error) {
    console.warn('Gagal memuat data NPWP dari Firestore:', error);
    try {
      const stored = localStorage.getItem('npwp_records_v1');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  }
};

// Save all or single NPWP Record to Firestore
export const saveNpwpRecordsToFirestore = async (records: NpwpRecord[]): Promise<void> => {
  try {
    localStorage.setItem('npwp_records_v1', JSON.stringify(records));
  } catch (e) {
    console.warn('Gagal menyimpan NPWP ke localStorage:', e);
  }

  if (!isFirebaseConfigured() || !firestoreDb) return;

  const path = 'npwp_records';
  try {
    for (const rec of records) {
      if (rec.id) {
        await setDoc(doc(firestoreDb, path, rec.id), cleanUndefined(rec));
      }
    }
    console.log(`☁️ ${records.length} NPWP records synced to Firestore.`);
  } catch (error) {
    console.warn('Gagal menyimpan NPWP ke Firestore:', error);
  }
};

// Save Accurate Petty Cash Mappings to Firestore & localStorage
export const saveAccurateMappingToFirestore = async (mappingData: any): Promise<void> => {
  const docId = mappingData.id || `acc-map-${Date.now()}`;
  const payload = {
    ...mappingData,
    id: docId,
    updatedAt: new Date().toISOString()
  };

  try {
    const existingRaw = localStorage.getItem('accurate_mapped_reports_v1');
    const existingList = existingRaw ? JSON.parse(existingRaw) : [];
    const updatedList = [payload, ...existingList.filter((item: any) => item.id !== docId)];
    localStorage.setItem('accurate_mapped_reports_v1', JSON.stringify(updatedList));
  } catch (e) {
    console.warn('Gagal menyimpan pemetaan Accurate ke localStorage:', e);
  }

  if (!isFirebaseConfigured() || !firestoreDb) return;

  try {
    await setDoc(doc(firestoreDb, 'accurate_mappings', docId), cleanUndefined(payload));
    console.log(`☁️ Accurate mapping report ${docId} saved to Firestore.`);
  } catch (error) {
    console.warn('Gagal menyimpan pemetaan Accurate ke Firestore:', error);
  }
};

// Load Accurate Petty Cash Mappings from Firestore
export const loadAccurateMappingsFromFirestore = async (): Promise<any[]> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    try {
      const stored = localStorage.getItem('accurate_mapped_reports_v1');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  }

  try {
    const snapshot = await getDocs(collection(firestoreDb, 'accurate_mappings'));
    const list: any[] = [];
    snapshot.forEach(docSnap => {
      list.push(docSnap.data());
    });
    if (list.length > 0) {
      localStorage.setItem('accurate_mapped_reports_v1', JSON.stringify(list));
    }
    return list;
  } catch (error) {
    console.warn('Gagal memuat pemetaan Accurate dari Firestore:', error);
    try {
      const stored = localStorage.getItem('accurate_mapped_reports_v1');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  }
};

// Save Absen Harian NMSA records & weekly reports to Firestore
export const saveAbsenDataToFirestore = async (absenData: any): Promise<void> => {
  const docId = absenData.id || `absen-${Date.now()}`;
  const payload = {
    ...absenData,
    id: docId,
    updatedAt: new Date().toISOString()
  };

  try {
    const stored = localStorage.getItem('absen_records_v1');
    const list = stored ? JSON.parse(stored) : [];
    const updated = [payload, ...list.filter((item: any) => item.id !== docId)];
    localStorage.setItem('absen_records_v1', JSON.stringify(updated));
  } catch (e) {
    console.warn('Gagal menyimpan data Absen ke localStorage:', e);
  }

  if (!isFirebaseConfigured() || !firestoreDb) return;

  try {
    await setDoc(doc(firestoreDb, 'absen_records', docId), cleanUndefined(payload));
    console.log(`☁️ Absen record ${docId} saved to Firestore.`);
  } catch (error) {
    console.warn('Gagal menyimpan data Absen ke Firestore:', error);
  }
};

// Load Absen Harian NMSA records from Firestore
export const loadAbsenDataFromFirestore = async (): Promise<any[]> => {
  if (!isFirebaseConfigured() || !firestoreDb) {
    try {
      const stored = localStorage.getItem('absen_records_v1');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  }

  try {
    const snapshot = await getDocs(collection(firestoreDb, 'absen_records'));
    const list: any[] = [];
    snapshot.forEach(docSnap => {
      list.push(docSnap.data());
    });
    if (list.length > 0) {
      localStorage.setItem('absen_records_v1', JSON.stringify(list));
    }
    return list;
  } catch (error) {
    console.warn('Gagal memuat data Absen dari Firestore:', error);
    try {
      const stored = localStorage.getItem('absen_records_v1');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  }
};

// Delete single NPWP record from Firestore
export const deleteNpwpRecordFromFirestore = async (id: string): Promise<void> => {
  if (!isFirebaseConfigured() || !firestoreDb) return;
  try {
    await deleteDoc(doc(firestoreDb, 'npwp_records', id));
  } catch (error) {
    console.warn('Gagal menghapus NPWP dari Firestore:', error);
  }
};

// Set stored config dynamically (allows pasting from UI setting panel)
export const saveAndInitializeFirebaseConfig = (config: any): boolean => {
  if (!config || !config.apiKey || !config.projectId) {
    localStorage.removeItem('NUSANTARA_FIREBASE_CONFIG');
    firebaseApp = null;
    firestoreDb = null;
    firebaseAuth = null;
    return false;
  }

  localStorage.setItem('NUSANTARA_FIREBASE_CONFIG', JSON.stringify(config));
  return initializeFirebaseApp(config);
};

// Clear config to disconnect Firebase
export const clearFirebaseConfig = () => {
  localStorage.removeItem('NUSANTARA_FIREBASE_CONFIG');
  firebaseApp = null;
  firestoreDb = null;
  firebaseAuth = null;
};

// Load initial config checking
initializeFirebaseApp();

